language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
#install:
        pip3 install coverage
        pip3 install termcolor
# command to run tests
script:
  - make
    coverage report
